### GET ALL
GET http://localhost:3001/api/notes

### GET BY ID
GET http://localhost:3001/api/notes/4

### CREATE
POST http://localhost:3001/api/notes
Content-Type: application/json

{
"content": "asd",
"important": true
}

### UPDATE
PUT http://localhost:3001/api/notes/68b736c573d82c22a122b5bd
Content-Type: application/json

{
"content": "asd",
"important": true
}