### GET ALL
GET http://localhost:3001/api/notes

### GET BY ID
GET http://localhost:3001/api/notes/68bb2f2c05fe37199a87c55d

### CREATE
POST http://localhost:3001/api/notes
Content-Type: application/json

{
"content": "User id of the note creator is at the start sent along the request",
"important": true,
"userId": "68d518f4c44e0dece2fe4765"
}

### UPDATE
PUT http://localhost:3001/api/notes/68b736c573d82c22a122b5bd
Content-Type: application/json

{
"content": "",
"important": true
}

### DELETE
DELETE http://localhost:3001/api/notes/68d51aba19e4ea5e1ccaccb7
